version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my-laravel-app
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    web:
        image: nginx:latest
        container_name: my-laravel-web
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: my-laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_database
            MYSQL_USER: laravel
            MYSQL_PASSWORD: 1234567
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
